# Generated by Django 5.2 on 2025-05-01 01:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_review_name_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ratings',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
