# Generated by Django 5.2 on 2025-05-01 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_review_created_at_review_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
